apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FaU9iEHWMWBJO2/BOsc9Nwc23kQXoLYrjPoaUeX9hk5msf3W/dcNZWvvSbzR59YcuHGl9KazgRAns4XfzuwUxKI4Iw==,iv:jdhl5+gvTEPCudN4WgYyoAu8AmIcsw9uGuEMVlPKjTA=,tag:F0epqjSGDyFhqeRsqkjc6w==,type:comment]
    tunnel-token: ENC[AES256_GCM,data:chhsnu1kecQ/fjrpw7bPbYDgIgz/iBBEC/Wk16uzw1KmctC9Pr8IfuI16fIZ7vZ30cW/MdIKRtu1umQ4/TrjFwJ7UEvztdc3UFR9fQnGoRgfJKKU8TavMSR0dm8qboGnpx2lsrE6qFTa4qPmlPkmdqI5cs4YUcXyqmxkNMpfPhmEgI5dbHFIHut65SPsQMXfuPcFLCNY1j8E11zpUHJsqz7TomK489Q2Ghsod8t1Uh2ZgmJB,iv:ppHvUPSQBLMgkw1denwOEbu+POhOKLw7FEmJKtZtaa4=,tag:RK4Wqxg5W0CFGh8DAY+JEw==,type:str]
sops:
    lastmodified: "2026-01-05T22:45:38Z"
    mac: ENC[AES256_GCM,data:BX2mcq2CdHSXMsgmV+fbGsQEf6emeEgsbo18yrmDaaQdz3H0/gFC6+ahYYaa0xOCqva+Laq6bJSOAlshQ9m/wVFQ48CboYjY6mzadv3jWCkpd6K0aS4h+5ybpNunwMVNfFM7ezP4BeIgyub0KSKak/hr5ihiRuMoUNN1J7wGgoE=,iv:LTn/9uILgh6pDV9lpNPlCjHPVN07hOVuGKdWWY0ial8=,tag:99vFYiS1dcf117CQyuowQw==,type:str]
    pgp:
        - created_at: "2026-01-05T22:45:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//fpYyk0bikJRrhW0zo9Mii79e/08B+h39ls+mj+KRkoDG
            NNxSUA0b3CatQu+LSfH43OiQuvIr71f+TH/OvMbdcG6F17JUBWrmJZg3Y4jI5udF
            J0p4xBuLYnitXyhTT4LO0AUlR94L4yQSoRgyQttpVWjIW36eYEqwlLNkkr5agFxx
            3UZz0ga6VaZjhVOa9GgmCKAEzwx8QaVFTAWMfQVs7PynlIdw8mWYNGV+qRVOEARz
            GmGORADCHx5MVHmPIOKdRUFfwxSXhImGiBabVQKc8KG9zUfGqFkvhff5hImhOwvk
            KmzCcpBmIdEL2satvIDHydvRNHV5FfkUhA8vkG3QXb3FdIRo7Q8ZJ1OEcooyYA79
            8sHajb97Xd+4Saxrg9Ax8UKijBniuzcoEqMYb44gZIsEHr5mXB7avACuGne4ESmD
            3K6zIn+EZ/fV0uqp4VTiHNmMmD/TDjV+qv7R9j2w0xZAQn9THKBLWS5HmFi/xORS
            EIbta8M0BZ1GqKkPpVWPntYsEg/IIDEVMu4jEHZ5Y4/VlSNtynXmoAHZ/UZI/lwj
            SymWSLnTxdI6cqhle6tQezc/JChI1gTpYwi+iefiR3GhDApUAe3tCJiy2nGmvP3w
            7crILbOrES8vfg7BrR/RuF9nCchxqjOoFfxdmTBOLacJqZxBWBK4YRnynOa5EdHU
            ZgEJAhBItH6TubBTtqKlqPn3Ufn1Iq+Ho3QAKBEHQrkS+pkAVm6+sn4wNujwtEdS
            x/rYL+OKQZi6ds+O1wlpaHZkhQKAzzuS72u9rfQ/RNTGkqMxfTQE6DzzCC4TxiSj
            fa517Ldvnw==
            =uM+O
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
