apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-config
data:
    values.yaml: ENC[AES256_GCM,data:mE895v3Z+EKi7wIuH9vY9yEXC7s3dKvr8hPlDOYpEajFx6nQdL7Vjjk3WkQ6HkakD6GYgX2BypfH9p0cZIMeQEnowuK/rDsNfPRYfZLnlbO0iyEkf2Ya2z8K7uyEvLKNAjUqsuzN7wcSj9U0FHVZC49l9NXEDetbbbd8Cpwa4WCnSnRiYC66I49DIsdlrOSTSQ9MBSg2gqCU6BKXhuwx6GfzwNmn3MdHuU+iRHhXjA0UBqSNBYFtG1iMOJuzfAIXHW7hEJCp9J9Vgpvw83le2QAuUU6YVWKDfBrQbFi4m6YjWlqVQMSlW/au04/01x/g08OVHChpbxuK9I6FDBhhd5YLqReZ5ygaUgOlLJz5Gag0LnaYqVxQq9PVYC22RSixpgll9WEabrnLQH0rK09BweYsunvfxPQfX8LQbobfBse+TAipxTiljSegwZ8RyubwHrTIooetA9WXL8bhQ+eBAl2Axu+FU1m6VK+MpYTiJX18TjGSoNVdHMiHun6Fb+YQuKjmdivQK0vOQzSnPZE0leUy9nbdNIPTtZg=,iv:vH21nd7LLbxjGGvqKSSxX71c+lWNeD/UNI2ZaNEEAqo=,tag:N8iX6xi3KKIVvJ6pGvLqAg==,type:str]
sops:
    lastmodified: "2026-01-14T13:40:56Z"
    mac: ENC[AES256_GCM,data:aQSbRdI3HE5lpIy+rzfXyq05tQ1C1MS4nUwgvl6334yALnoJHZewBZH5OY/Sdgad2fB4csZ/an77OIlR0/O7pD5x2EzyjPdHJniAcBzRdIeTqPYen5SwnmhQ8JhaKOlHI/yfSGSXwJGBctLM12SH6mlRa0YiQxsvS6pO6nHTUTI=,iv:LN6ZokDf3HZpzmHL0o81ZNlkEjioXB68ikjK8NrP58Q=,tag:e3kk2F2ZxAt/wVWzwjwcJw==,type:str]
    pgp:
        - created_at: "2026-01-04T23:17:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJARAAoAQ/JfsD/zOmu+89pEz8su9LUbHE0JgSK5Ehw7bD3yMW
            2SaLljFGiJCzxdhNAn5UuzeFLHwWtULNxnWOouf7xii2yv/0HTN7TmJtaN12vv6/
            Sr302mex8YRjSU7JB5tSTN81XCtvtBuYXx7ycShhWjszHu/qcF3r7OMNAwMJkGz+
            bN8++KCbe1RZiA8uo87THtUhxd/57ioGcPsHQMmRXtcLbeNVVOP7yiv0WVmEYSHO
            a+h6B9vYz4aGw7S4yJeNbhthziKyXqoKUN0dRF0ro4cKZUJPZ9brcsTmqSo1n4A8
            2aVX1Se1cso72tYfeh17HczKy8M7JZg5yEQXVexD0cyNLKEq4znbC7t3f3X/nctu
            BU/3OrQ9V22B2B6YjA4WQZ/ay29z3KZpRRZM6CNgrMHy5i04zPEQ78LiuoKn3u6M
            3U0PlJSRdb85GGUKcRqR3ZNRiF6JCxmTeY6pzMqRbZKeRjxB6ql4JJSkYn86rQBy
            1qFZ49Ymlpg+3EsbjhySP5tlP+Z5+DQrlMg6+Sp2zzY0ZlI5UKjlmmEtNt66NGD9
            ZcITSrkPwJoGgO5RfPqP5n6fMUpQBl99b6NyduYTPyoL7kHgvb56Hw/EvUzQgEUR
            6mYrUt941d++xH1/xHbf5Vgkw/P/IkJdpZtb8HG92bITYXgLyw/oq6MqVXNVmUjU
            ZgEJAhDSh/JEV08DIrQolvSYMnddlQ0ltglSC04CfXROljKdid+S/Pwm3JiF0YLF
            oSb4mqGy040S9hx9+bECQ04YzlbcEHkt4tMh9tPsASSENid/FMfKwKQr7ZeBivWP
            up6/eOulTw==
            =Q7pQ
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
