apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-config
data:
    customDnsEntries: ENC[AES256_GCM,data:dV5vtTMIFwQhWAmebsSTWqJWp8VmXOEQEeNc+c7sw0I6dBMsDM/qC5ipvaGya7UhA2SAU153kI/FoIpw39PuIZfL0WJKg+JrGLchjv7xawme9lC7QSiXaqsWFe9GNQuB1CeTRNwoIKc3HMSG3IpbYU+YNnbplSSURNRPWXy3c3YVAbp/PGnc46Bce2U8QTlCodLndTU+BhCLyFbjumK/go/gFh3bwvtVQ2X3+2aZBDGFHNf7FNdE/grX+SrYyTMikNClIPck//dt+LNY1gUwQuro7j5PmH6CvAbf5S5shchvS//r6RyF26/At50gkd0Ori+tqHyJiix133+dc0s4w6Yz1Z4Td0ufVjR0KxE0CGL5j+jS1rZuAxdCfp8lmyscZ9fL1MrhqIkYFzHHJnka5fxBWnwHtwjorKNsImhWxU64qovoKPRKo68drIqmtw6U+FmU+QghAkqLoe0qDw==,iv:zkkdr85wVujbtrszZvnO+Faq3SZRtYYuR0HhSqNEAWk=,tag:xafqlBlDeoXBqqlOXeeGog==,type:str]
sops:
    lastmodified: "2026-01-04T22:57:54Z"
    mac: ENC[AES256_GCM,data:3hPxBh0ESbTaG8H/fsMUmD+YULz98imWfMMQooTpUdlbzEgUi+HJCAQJyJ4OgbCWDFBIhUa/jnpcnAdkhYs6gfUCL/jzc1S6iHocu/I/hIKpkWM6sQyg6zCj+87in+hMI+iY8NsSKGN+JcZGApClLttkkV5jsS8/bQ19YHr+fZs=,iv:rFS0XvSxqNnp3X63ORZ/T2ij/iaH6fk2BKpZoilC4wA=,tag:bvwJ0jR/6UF9BG7EzwuBgw==,type:str]
    pgp:
        - created_at: "2026-01-04T22:57:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJARAAkQc1leZUACsR3btrqXlH8S/avcuIHitg9jNNDpHcBEri
            J2nGqPvO/rQJwwwZJeUVdnp0TGrGCySWkihJHb329ulyB3hWoAGckPE6SBl1P3cg
            8a57AhEWUz9U0nfr95LoWc4qX33tIIcKg4lBgnFsLTzQkhWs1nyd6cT0cvEQXbrp
            2kSAoxkv5acrWzNnebkti0MHg2d4k2viuiPfUZ6pYQf8utlMhc/8ktYcmLwRX8Vo
            xaQ6RWg978SbXml4KHPHhRtk3MZPXqz683wdcn4s5YJ2nu9lbAWxwO6SIshxU9xn
            yUT6AksRk6geDMNExAh0XRU+Fm6MJkNLVCxDY+SKWIxjXTTfpLJwVx4S5Fose7Oi
            uBB5k1O3WtvPnPnSF1O3AoleBFHmc19KHa85VMCn1tglvePRFvQPzcTzWLIwGBj7
            7MJGsPPUGEqdzYb6+lDYWe6gFhcwshpbvrNTxzDx32lX7NKjNWXe004tDb7Rcm1P
            Oho6RKH0ZcemVeG02QNdGsxobUwJHnNyqr1V6PUidM7ktyusGhjfYbp3bppsd53D
            pnHAaJpP9/BiKc+aMG8RHlwrCLVcGLJB9q8h2NpbZzxkJ1qNHp+c9zgom3kmOuLB
            bNZtw+M0YulkAVLXsd0FZ8FsMk9y/hhwt6TH/4EvFJ7JjAS98nX9XPIbRDQe0MrU
            aAEJAhCc7Jl0AtZdSVJjAg+rD67MjQ9Q49b/+Uxynomo0grKYnayrqwWCKi3+1ry
            Wg1PdFw8EtNxXFtdH6VA12YsxwwE/o020Z5GNsPR5cFqTcbybNwXOnVqN+fJ3gN0
            2AyADr//Slw3
            =nkGp
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
