apiVersion: v1
kind: ConfigMap
metadata:
    name: pihole-config
data:
    customDnsEntries: ENC[AES256_GCM,data:LiXlfGyvRqQv4dFUWLoPRd1fL2srAwDmKcjadKOlzLFLilQx6xtHoJUFhVi557xI5DgmJ8fCrEO6PUlD+ggxxKpq2N4ezvzFdI+SRoywzn59yVbSLqUB6fr3oZDyaLU7OWIBIM5X+c+aDQmTzbVu+3j+GOYIFEi6diJLLyQe3KozOCLMc1K7CqZVFblJhPslhHXVA/WI/wcaJV7kIu//EOBj9n397DSoDxLvQ8Esg2/C7SKuV9DBZWW02reFWMWJg8qAuVozVntiR1PztJnmiHI7+YMXQX2Qj8qkdQ9op0WbiQZ3TXpv/AEt7NuWfFmSBx4roT/Hlk3n4lBkpsgvJ6F+fIywtOZvKVOuAy9sTz+O1Jwo8FYpDf+x0SZWyFRXPH2/nHcRxF2CPwEYhMszESu58Ka8muTufbUxpnmoPnLFL5zS1IKrWmUAIoSJH984TvOQh1eRKLqEhoHmxQ==,iv:mARkNZQ1MK1yx3GYkiJJCLx1SWTQ1fmY653s6gtH73Y=,tag:Fw5OWGjtbiMxAo18yWrbBA==,type:str]
sops:
    lastmodified: "2026-01-04T22:32:51Z"
    mac: ENC[AES256_GCM,data:UB8tXmSkxZQIdnsPrFsca4WlXQVZmhX1fehiNjJxzxuadT2kZtYUgPiZrzRE6CjFTv5Yuz3X4LPwRWRIwS3GmASi9fxwL5WOqPnFU7kf3nbBov9P5cwZUKy/Bs6At2kb79UPlv2hw4EWG8Q0r01bxN+KCdHN97JHpjtj3XYrEbg=,iv:hcHv/ahoIkoXGAxUwzuocVhyxHgOweeOLWxUJbXyBHI=,tag:UZXaYqoWDXqMt3CjY2lEVw==,type:str]
    pgp:
        - created_at: "2026-01-04T22:32:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ/+P/3l8WQptKNL5kVN0wsYKHif2t1oftuYACTCz2fOMdCV
            11Ui885FoeqwnG8QKrcxLq0rx1t4rwx1mhVavlIOfb8WTLijZgRddFE/bXyEIoJV
            +Sda1Gh6uKiUWRrpmn4z2kX18Y0207yhknJghlDG28A+bWLv4cPqcCGNojuQ6/63
            e6OVZWknEdcCj+G1R7EBQiNC3yOXMKuRT4Ob4FebmBg9B79dBpgcWJyItQ/ljsOu
            OUTEo5xp0qlglolk+Keom10c0Sdqnhxur8xXXssR665Bt1ruJ1b9dmSnAGdqzqy3
            Q6N4tbVP/15jnsYjQTWbf70e6dl9EuGr+L/xnblSXHfjdz6+PVq7QBlhh/ZW8kcx
            Z8+IXhKBsUrL5D6/fYFUdSQUTrn8haf3QZB5pXfhh7jSd8ungMNQ95C6Sv9rYVn5
            KtRnFUHyfwpczy79DFa/yo64huDJly9M/dU+KdOu5Sj4fHL3sdFSWpeEjyzSIbnj
            P25LHD44pFBQnLozGz3yDuiQ1524ecj7kvSymAODKvMcohuAqLGRJKXDbUHSoyxv
            OJdQVOUI/NG4PbHhiArvMgxzXv1yQT2TTDw7AqYr5Ij60uS4sogJ0Sc+zC3BbZeA
            yCy938JO4BhwRhLYg+Jh8QGPZNa5cq8UvHMvfqiOLR3z0BS20c/2yqhKh7+d/kLU
            aAEJAhBY9ctraqkAqGpY2XJGS0z9dDG8QJwmgWWdmjVHUuy9bXgue8jSuP2+jpH0
            cu7YPyxza5vfL4Qx7GVNYklAOtzXzTrwYvEXMDKFdxdkWw6pY/AULo6NNj4fJMhv
            vf3CHjukuXf9
            =eaVS
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
