apiVersion: v1
data:
    server_countries: ENC[AES256_GCM,data:wuhr1f+Ex2Q=,iv:Bna7rZATmZqGxw6K4g/tUV2YH/GsRghoXhdSl/DI/kw=,tag:y+3h7fG3CcQD9JlxRVdFLg==,type:str]
    wireguard_addresses: ENC[AES256_GCM,data:+7e8yNhUHcsF+vE4jDU5KK/dp550kxES,iv:U+qVxpUVuaIVu13Qv42f3P9a7SThX1hnCKy1kK4V85U=,tag:vsVuRb8Vi9aD3p7nqs13sw==,type:str]
    wireguard_private_key: ENC[AES256_GCM,data:+YvimmaWTkADlGHhvr41XQVOqzOJPjuQBU1XnX7jW17yO+Z0jIM5ReOBkA56gG/btIx/+gZM6Jh9fNU5,iv:y8WD9tb8nIjaMSUlMYLuixdvyjk2ppbHvKRVqstbDEY=,tag:4tc4MXKVXdozRcjC9UXzLA==,type:str]
kind: Secret
metadata:
    name: media-vpn-secret
    namespace: media
sops:
    lastmodified: "2026-01-13T01:33:16Z"
    mac: ENC[AES256_GCM,data:2cucXijOgwVH6vkoNbA1meZzKH5Lv4AmhKEqscXtqaNLDLcLJIfwfvYxfbDzMQkb59GTvmUd1SZjIZZ1gc6n+bWjdUj2rpGgPReCIVRcE91oE7mtePH/IN52jScBc8XVz1oOCUJ1lXqx5jX5Xv89NYjw88qmp3BHBs/tQuaWVSI=,iv:t/AOBBrYjDP7Zt+0aXLes8dz7TPewdJYOYmvkeZ2x2g=,tag:8vYBP9CmKk8nB80yV1h90A==,type:str]
    pgp:
        - created_at: "2026-01-13T01:33:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//XEuhuC90QDB0pNtzbKXk/+YevZ+gW78Sb/JXTeEOXOtT
            eBpoV4m2QY8QwTsizM+Q61qLOHN9BEsyUoglC23cc/8fh3A1Sl4SdaRBa1t5tKMS
            LS3EcueEuMxCNnoBnGpP9KB9l3mk/jlFOuOU7ZWLh9jiXs6rIIyPg54nGS7Awtgt
            CeKOAFqnQ67vH6Vv2QZDGBkJCAizgjgT+8VJm17xXDUW9GvRh6aPIJQPMmSzVvYN
            KmqpB5xhJv63XtGKB3kAgLiKdcy9TFMq8MGmQKS3+HCoUK1LH7dYCFQtV44HMNXS
            otKC69kj59wI5cwjYCFXjynd067l3xz2aFOvIVtrHpcDanwfrsi4Pvh7AOKAcxZR
            8HPF1RdPkTFZakT9WgTAg1nLyG704/vp4wAyNxjohwCTG1SoZqq4Ox471eq03sD0
            QQDLcNGjH40LysABYeKDPm1FXNMCGN4YeKpla2ki9yNSWve+RXCPhi/XWYq2ZsGY
            ai6FUNX5mRPx176qz7fdP/vVvoF1QiLbVmKLsPOV00hl+QfaPS7dJjxzR7RjOOOI
            1nEoK0rHKYxYEd4rWNdxTRWqYStrApush3TRJ7DO4Y9sr490a38RCFXU6JQYa4Vy
            whmKMrmv8DDZ2rIV5UZKQFnMglIYXzgi3l67oQb+3FmeC1Btla4SfWvkL4N36ZXU
            aAEJAhC7LXKT2UdQE4RZAhjvYBhEolTfDMgY+t6o/FbawORNX3OJh1zOmbEw7XgG
            c7//ivOElI6NdulW65RM2BPQ5Bg/yU3ykPhxh3PTSs6USCpPKD3wGZ+uuIjBj+Cc
            ImcJb/s56y26
            =THVN
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
