apiVersion: v1
data:
    SECRET_PIHOLE_ADMIN_PASSWORD: ENC[AES256_GCM,data:10R2mU9bXWlgbj7/u6bZkBSKoNo0TjW5y/V0iCyG8u0=,iv:8J9FARuSQbxpDd4BjiwOTqhZBXvS0UuxwbYsSatoaSc=,tag:evl/xqRCacXmB1azY8CT7Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8mMPIS5I/6hnGaura4xvGdthqJAkkZmgNqky9Q==,iv:ViiImxtK21y+1p9cYHJkUVaxUosvdP4rhUyzdObKJFE=,tag:mEJVJh9oSXDM62CF5mwUhQ==,type:str]
    SECRET_MEDIA_DOMAIN: ENC[AES256_GCM,data:RfENWLKgCttEdj5Ikxk7Ydf0I/xjaJqKji063Ozzhss=,iv:Kd9c74I/ZwYXcSNNpp5p3tw+D1QUxGpp+BBaUZBXGR0=,tag:nb/+xhjMYK6Mc9ql6/3trw==,type:str]
    SECRET_TRAEFIK_DASHBOARD_AUTH: ENC[AES256_GCM,data:fYWmTjV5ETGjKIsyJlMCCM+dCy2xJAyv+exYOIfY7v/unpVMu1Ud1cINFKEs2rnzSltmweBvA2s=,iv:JFvj/72uZ0FJs/kTZx6WkxK9nEM+1w9SlOeM/6VZPBI=,tag:JJ4I9y+/EQ4ri0L1LkFF9w==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    lastmodified: "2026-01-13T23:45:54Z"
    mac: ENC[AES256_GCM,data:280z+njTPdd19NGYJeju54xeYxIaJxz3lRwVmF4258qYsycc/58dXXHisFlCvtu9CgIa5yhLVAumBVU49BIZlKa/bGXREQQarHzfVXn1+nzeNBnrObLx1RbZOuSKplCFWnHQczvSrcSAfC+SBhX33quVQCQlIYE1+ou23PS/JMg=,iv:jQ5dZsKJq1ZhRVKKzuaLJpnFaNLa1LyQMe8Rlgh35NU=,tag:nUq4BLGXfSk2YnEp7+1Vmg==,type:str]
    pgp:
        - created_at: "2026-01-13T23:45:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ/8Cg/5zpZ+m5fQds9LGuUhIzt1am/MTP8avdFGaHfHJw+l
            Kn2BellpgoNSORW4YuRru8NWCocJXXm6A6eQ04yHfn97PvhGDQHNI4thEF8XX+en
            V6n2i/8yketfVHx8jYtR95xxeee8zVUOU6w2adNfmwbRp8V902xX6TaAgC9SqJUg
            lVO5Bf+GDQJq83QbOaQw2dhTMpJpX6rHb2I3BtOdH3a/6CB82JcW/tqy8fDmND4r
            kBs3QfkicA0YLi4RLX5vAhdGSIJGcWMTx2K4fQdaP4cDWjfSfRIUW2r0ejjGZdfT
            vKLWNpehdO4TfVGkRFGZB4ySoad6Dp8cjKNSJAzapTgnVUqPhBvJ/9pIhUvWwbul
            LmoypDqaO2GoYkmYpqSyafZo/FohHp5k1wRQ51bdJkb2VE38jaOgMLd8q/8fJ7zq
            cvdzeFMI46MJObXkxiipJcPhe03GGxQV4pvLagN/nCLTMHdHolbHltIn6MiY/SAT
            x+13doCm3n1RCjfDsfGFwLhsBFgtO6ikor7hYdQs0kbz0vytz5jzYfQkwBcxEMKD
            EFER2Mxf6iVxCFMjvlXlibfr0F9JsliF+l3fa2dOILr/R+mypPWVIPDYyChD8YIl
            HTAOXcI/pTjIGVAEBCLDI6bv3y6I+uxmjEI62z3hSAKZ7qWSPh6cTDcBxCIhCETU
            ZgEJAhDuUEQLu2YnIHaDkKmLMcK4TevkL8JsCFYNuuK/wbs33cDULi4oeGBU1/AA
            LcRbsg6XRuATMA16yIJs3SmE80O0QSePClteXAKDqZLgJrt3GkX6fv4i9Wsnw7Zf
            I91tnR48Mw==
            =p51r
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
