apiVersion: v1
data:
    SECRET_PIHOLE_ADMIN_PASSWORD: ENC[AES256_GCM,data:oDxUj51JkEmi07jeL/jDxINI+37xKztMbcI1iFNYTtY=,iv:efE/TwAmuD6xfN17v7DPfhOCINvARTmnYvATt/frqX4=,tag:CNNHh9lYlRSjmLBehxp3fg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OFs5yHxpjTEMo4VTG6FgxyPrNg==,iv:cfTEZvBnpGblmzttnpSeKcnOBdrajCkSt4uL2Xe9Vcw=,tag:dR7kYUwHqdtjdazxvHVY/A==,type:str]
    SECRET_MEDIA_DOMAIN: ENC[AES256_GCM,data:ZYtsTVfXsQ3MijH1hmK/m59QB5rqfg==,iv:qB8oaUfLKjQ0ZES9xwE/EASgmlZYon7WheGCO9lWkdY=,tag:sTJgydVytiDlYor/+8KNlQ==,type:str]
    SECRET_TRAEFIK_DASHBOARD_AUTH: ENC[AES256_GCM,data:VSPzMaSxglGgzn4VTHVgTnqGhv3VmtzrcehnkaNX97XzskjmO9Teb+rA,iv:aaPv2jxedmUu9HzMMYpM4Y7JBMIBNZy35pBd4dJKJ8I=,tag:JcAvCNEK67lRXLiaa7yiSA==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
sops:
    lastmodified: "2026-01-13T15:57:07Z"
    mac: ENC[AES256_GCM,data:WIWTFIWdrFeAI7IL44jKPcT1cIZoAJ5dfaJKpAoFoI8859LyCKLY+F2rMASl6l5cWLlcEDtN9+Htqa/ES0bR3fG8Tv0k9oReQqQGSOcnbZh2ElN16FnVxNgjT+n1O+uYCWXMNeBA3z91Zdde/ebKus8Lq2qSAdx0HXy9Qy1y1vs=,iv:2Yom/imaT4CccylKGQNRHJsWA8cAdNQ673H5EJebCt0=,tag:Cpeo9sD6WJPBK1Ic04C7DA==,type:str]
    pgp:
        - created_at: "2024-04-19T11:46:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJARAAlkhWOp1HBp4tyAphxFsfOHtTnAWSZnbpszZwlRt+6Kls
            pouU0KRxWZby/EisVXKnIEBwfzu01cRToaoFkouOOjhmGNg09xSjix9xPP+nA1yI
            Adq9Y6yFuZcdVyIUm+AIGJCmLJquGz0vlH+OsPRdprIj0exlMV4dJLp90QwvGSAn
            qUMlsPT0pc/MfKKP8st8AAaW0O9aon7QHCZ8/7v4maQzCyMZpGDhiD91hznT8HrW
            5s1ivNCu6nx6IuOh1w3Jizl4p2XmlHOkBdK7n/lkGe7IZQuwLtb+oB7NybKzJ3OZ
            2EBpvJmYhn/dFZJHmAjjKarZJVInvGNviZU0TKUP+LiSxpbjlH1tg8FfUY98/zE5
            upFkiGlEImYcxB5/CE2mhzx9qrzQIjCjou2j5jpjVnbqxeBmJO/jaYoi3eSlE7R3
            rAHyIzB5vQ642Kirv35a3ypZ2MOiV1RpqrkLDVRghmFQo3Jj4nSnMq/CWs317pKz
            6AWcA/UQyVZiOgBTRKvRJ2pcbWyPVsS8MmPyQI8FjT57uQj89TesuzdPI+S182vE
            tItdl8319exKJO6oNQqujTxkRLjGarORlm8IIxL/IBr/CHJUG8aDnf6VPj/DTnjy
            mD0GEAwh4NE/aGeXFBVokoRtzST3xWLoRNNbb2YK8o23v8TBMIsi3dk9nCO/8oLU
            aAEJAhCcZPcdKw32sjCJlTfzm9JrJRMXMpiUVS1acT4UGlqEBFOFdkOZKDPipTm9
            b9qsQwEFKOZdFc1oOJHIU623CmjEE4nFdIxi16TKj7Ebl8UiLDuquTe5ejo4seru
            SEmkR79TTAP6
            =Zoib
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
