apiVersion: v1
kind: Secret
metadata:
    name: ddclient-config
    namespace: ddclient
type: Opaque
stringData:
    ddclient.conf: ENC[AES256_GCM,data:biFgwMbJ6/w+J+PFqL1ZDCmf4ISKoovy7Og0adxkRzQvLN8z62Alhm1HmOMJDQM4nU+Tlrfu5fBsmKVYDkCT9JIZftSAnOaVyb1QatKVumLmIKMojGMOzDhKGPfk4/q+cAM7ZdyqAwEGlL9g8AyOBWhWueRZNnSgEEQ+yo/ecbbUa//7w4YpJQPAcyQYijfob/8LLa8=,iv:uyPDUjEUmeqJ3aQ20SJkUKH6qul/YTJEzG8EHezWeWI=,tag:4K20ckH2mOJ1Lxscchv0JQ==,type:str]
sops:
    lastmodified: "2025-11-16T16:46:39Z"
    mac: ENC[AES256_GCM,data:9M3W0yIHy0vyx8bZs98IRZAts+xeGUmmqftU4lDX1ZFgbDaS/dZUHyOo/Cl8dhczMfmyZ3VVZAmf7xfeG9wxfdxH2GMn7IBXMScFjzbasjpEXaJzKl8YAyua6nzw0ms8sMpLvhO/AOE1JFJXfTeT+XORO7u57GGgu59EiU/Q7xM=,iv:Q8zBv8gW7DjW2SXkVq4Yt4qOnfYex/2Dl9ECd6C5a8Y=,tag:Vgu/kqAGux7FtQvoKzPstg==,type:str]
    pgp:
        - created_at: "2025-11-16T16:46:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5FN4wzd9SHJAQ//X98pZmr7wVx9EF60e7bysLqkIP6tD8R2UZplPJ2DZ4fZ
            ghMA6WJWgZtsD5lE/q2bNd2IlGzNyoi9pSaOS0umvW0GVCgD6h0B35qekcKLPgUO
            UgjBOP4PvGmwA0TrPPAkyXrNCt22P/QaIvBm7di3RY2DuADHDfWMlCsOtnvSirGQ
            AZLgSM9pDMKZTU/vwxWLAFJ0+Ihoa2moQViz5MizXncZ4kJ1Pq/Ue7BkbyCQz1TC
            +KNscjbYBtUJ8q0vM6t5s6wr7tSk9US+ATC56YOI9Gi877yLkisKB8Gqe4pQyEf6
            7JJv6fw2q3z3cv46HiQ+A4eLwa3CWa4b9jL8q1OpmYOfyt3mfLul7di1fK8HGjYo
            lDVMYfwHtZCRAJMhbGHJ/5+onPWhEv/DEerkHp6Zfd+60mC45OqyXVkOYKdQ4f3r
            c6ZvkfPvOhGxrNThoO1psp5qFTor23NRSBTcnsKrYsOwkkqqc/MfP025YIFWX5is
            owDQqcJpZ0smx6tbGWK8eFlkVW/omk9aMSAyFNzS+6biCvlEeqvSXzUcCMd/zBVX
            faa+1vWwdWRzBJ1iNZLEnexYRXBtd9mP4cZAeGoZEiZfWLf4njAs7C6747R0SmHk
            k64foYFg8+TBZ1KriUIydv/20hTXKkykSojKnegtYw7RdTOE2RafJNoU99ta2OvU
            aAEJAhBnT36CI2sUQ7DzQAT0KUx8MokPMhgOsGBMyAg/rhTR2x8snPvls1Vnx0FU
            OGrFoDjlJvVzx8sjTqY2+e+U1TnDhzi5Q7cUtLHiCn1CIN1ZlN90cj0NzlqAGL1Z
            tEhJ7tK2x3VR
            =+HCU
            -----END PGP MESSAGE-----
          fp: 32C1F8EB0F2C663985FEB304D42593FC4B1C16EF
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
