---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-config
  namespace: media
spec:
  storageClassName: media-ombi-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
